/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


/* Types / structures used only locally (or these would be in the .h file for other modules). */
typedef struct StructTag
{
	int StructElement1;
	int StructElement2;
	int StructElement3;
	int StructElement4;
	int StructElement5;
	int StructElement6;
	int StructElement7;
	int StructElement8;
	int StructElement9;
	int StructElement10;
	int StructElement11;
	int StructElement12;
	int StructElement13;
	int StructElement14;
	int StructElement15;
	int StructElement16;
	int StructElement17;
	int StructElement18;
	int StructElement19;
	int StructElement20;
	// etc

}_STRUCTURE_ALIAS;









/* Local, file-scope variables */
_STRUCTURE_ALIAS MyStructure;












/* Local only function prototypes */
_STRUCTURE_ALIAS PassWholeStructureInOut (_STRUCTURE_ALIAS StructIn);
_STRUCTURE_ALIAS *PassStructurePointerInOut (_STRUCTURE_ALIAS *pStructIn);












// Main entry point.
int main(void)
{
	// Create some example structures in RAM using alias and tag.
	// "Instantiate instances".
	_STRUCTURE_ALIAS AnotherStructureWithOnlyFunctionScope = {0}; 				// Typical usage in industry
	struct StructTag YetAnotherButBasicallySameAsAbove;							// NOT typical usage in industry
	struct StructTag *pStruct1 = &AnotherStructureWithOnlyFunctionScope;		// NOT typical usage in industry
	_STRUCTURE_ALIAS *pStruct2 = &YetAnotherButBasicallySameAsAbove;			// Typical usage in industry


	MyStructure.StructElement1 = 1;
	AnotherStructureWithOnlyFunctionScope.StructElement1 = 2;
	YetAnotherButBasicallySameAsAbove.StructElement1 = 3;


	pStruct1->StructElement1 = 4;
	pStruct2->StructElement1 = 5;

	// Testing...

	// Pass structure in / out. Original structure data 'protected'.
	// All data is 'copied' into and out of the function.
	// Much slower
	_STRUCTURE_ALIAS ANewStruct;
 	for (int i = 0; i < 1000000; i++)
	{
		ANewStruct = PassWholeStructureInOut(AnotherStructureWithOnlyFunctionScope);
	}

	// Pass structure pointer in / out. Original data can be manipulated.
	// Only one 32-bit pointer passed in / out, the pointer to the original structure.
	// Much faster
	_STRUCTURE_ALIAS *pANewStruct;
	for (int i = 0; i < 1000000; i++)
	{
		pANewStruct = PassStructurePointerInOut(&AnotherStructureWithOnlyFunctionScope);
	}

	printf ("%i,%i,%i",
			AnotherStructureWithOnlyFunctionScope.StructElement1,
			ANewStruct.StructElement2,
			pANewStruct->StructElement2);

    /* Loop forever */
	for(;;);
}

// Example function
_STRUCTURE_ALIAS PassWholeStructureInOut (_STRUCTURE_ALIAS StructIn)
{
	// Do Work.
	StructIn.StructElement1 = 7;

	// Return the input structure back out again...
	return StructIn;
}

// Example function
_STRUCTURE_ALIAS *PassStructurePointerInOut (_STRUCTURE_ALIAS *pStructIn)
{
	// Do work.
	pStructIn->StructElement1 = 8;

	// Return the pointer passed in back out again...
	return pStructIn;
}













