/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// A structure the breaks down a unit16_t into individual 'bytes'
typedef struct __attribute__ ((packed))
{
	uint8_t Byte0;
	uint8_t Byte1;
}_BYTEWISE_UINT16;


// A structure that breaks down a uint16_t into individual 'bits'
typedef struct __attribute__ ((packed))
{
	uint8_t Bit0 : 1;
	uint8_t Bit1 : 1;
	uint8_t Bit2 : 1;
	uint8_t Bit3 : 1;
	uint8_t Bit4 : 1;
	uint8_t Bit5 : 1;
	uint8_t Bit6 : 1;
	uint8_t Bit7 : 1;
	uint8_t Bit8 : 1;
	uint8_t Bit9 : 1;
	uint8_t Bit10 : 1;
	uint8_t Bit11 : 1;
	uint8_t Bit12 : 1;
	uint8_t Bit13 : 1;
	uint8_t Bit14 : 1;
	uint8_t Bit15 : 1;
}_BITWISE_UINT16;


// A structure that breaks down a uint16_t into 'nibbles'.
typedef struct __attribute__ ((packed))
{
	uint8_t Nibble0 : 4;
	uint8_t Nibble1 : 4;
	uint8_t Nibble2 : 4;
	uint8_t Nibble3 : 4;
}_NIBBLEWISE_UINT16;

typedef struct
{
	uint8_t MODER0 : 2;
	uint8_t MODER1 : 2;
	uint8_t MODER2 : 2;
	uint8_t MODER3 : 2;
	//... 15
}_GPIO_MODE_REG;
#define GPIO_MODE_INPUT 0
#define GPIO_MODE_OUTPUT 1
#define GPIO_MODE_ALT 2
#define GPIO_MODE_ANA 3

// Actual variable.
uint16_t uint16_Variable = 0;

// Pointer to variable as bitwise structure.
_BITWISE_UINT16 *pBits = (_BITWISE_UINT16 *)&uint16_Variable;

// Pointer to variable as nibble-wise structure
_NIBBLEWISE_UINT16 *pNibbles = (_NIBBLEWISE_UINT16 *)&uint16_Variable;



// A union that combines all access methods
typedef union
{
	uint16_t Variable;
	_BYTEWISE_UINT16 Bytes;
	_NIBBLEWISE_UINT16 Nibbles;
	_BITWISE_UINT16 Bits;

}_ALLWISE_UINT16;

_ALLWISE_UINT16 *pVar = (_ALLWISE_UINT16*)&uint16_Variable;

int main(void)
{
	pBits->Bit4 = 1;

	pNibbles->Nibble2 = 0xF;

	pVar->Bytes.Byte1 = 0xAA;


	_GPIO_MODE_REG *MyGPIO = GPIOG->MODER;
	MyGPIO->MODER2 = GPIO_MODE_OUTPUT;

    /* Loop forever */
	for(;;);
}
