/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// Header for command structure
typedef struct //__attribute__ ((packed)) // Un-comment this to 'pack' the structure.
{
	uint8_t 	b_CmdCode;
	uint32_t 	ul_ByteCount;
	uint8_t		b_DeviceAddress;
	uint32_t	ul_HrdChecksum;

}_CMD_HDR;

// A commmand with payload
typedef struct
{
	_CMD_HDR Header;
	uint8_t Payload[255];

}_CMD;


int main(void)
{
	_CMD_HDR CmdHeader;
	CmdHeader.b_CmdCode = 0x11;
	CmdHeader.ul_ByteCount = 0x22222222;
	CmdHeader.b_DeviceAddress = 0x33;
	CmdHeader.ul_HrdChecksum = 0x44444444;

	int SizeOfHeader = sizeof(_CMD_HDR);
	printf ("%i,%i", CmdHeader.b_CmdCode, SizeOfHeader);



    /* Loop forever */
	for(;;);
}
